version: '3.8' # specify docker-compose version
services:
  web: # Define a service called web (our flask app)
    build: . # Instructs docker to build an image using the dockerfile in the current directory
    ports: # Maps the 5000 port of the host machine to the 5000 port of the container
      - "5000:5000"
    volumes: # Mounts the current directory on the host to /app in the container
      - .:/app
    environment: # Sets the environment variables (Enable debug mode)
      - FLASK_ENV=development
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=rootpassword
      - DATABASE_NAME=car_maintenance
    depends_on:
      - db  # Ensures the database starts before the app

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: car_maintenance
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mounts the SQL script

    ports:
      - "3306:3306"  # Expose MySQL for external tools like MySQL Workbench

volumes:
  mysql_data:  # Named volume for MySQL data persistence
