name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Runs when changes are pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub will run this on an Ubuntu virtual machine

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Clones your repo

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Enables multi-platform builds

      - name: Build and tag Docker image
        run: |
          IMAGE_NAME=felipema/car-maintenance-tracker
          VERSION=$(date +%Y%m%d%H%M%S)  # Creates a timestamp-based version
          docker build -t $IMAGE_NAME:$VERSION -t $IMAGE_NAME:latest .
        
      - name: Push image to Docker Hub
        run: |
          IMAGE_NAME=felipema/car-maintenance-tracker
          docker push $IMAGE_NAME --all-tags
